package lox;

enum OpCode
{
    PUSH_COSNT, POP_VALUE, LOAD_NAME, DEFINE_NAME, ASSIGN_NAME,
    CALL_FUNCTION, MAKE_FUNCTION, FUNC_END, RETURN,
    BEGIN_BLOCK, END_BLOCK,

    ADD, SUB, MUL, DIV,
    RELATIVE_JUMP, RELATIVE_JUMP_IF_TRUE, BREAK,

    LESS, GREATER, LESS_EQ, GREATER_EQ, EQUALS,

    LOGICAL_OR, LOGICAL_AND, NOT, UNARY_MINUS,

    PRINT
}